# Detection thresholds
CYCLE_MIN_LENGTH = 3
CYCLE_MAX_LENGTH = 5
SMURFING_THRESHOLD = 10
SHELL_MAX_DEGREE = 3

# Scoring weights
WEIGHT_CYCLE = 40
WEIGHT_SMURFING = 25
WEIGHT_SHELL = 20

MAX_SCORE = 100
